name: Daily GitLab Contribution Check
on:
  schedule:
    - cron: '30 5 * * *' 
  workflow_dispatch:
jobs:
  run-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run JAR file with Excel dependency
        run: java -jar GitAutomation.jar
